#!/bin/bash
# cai 09.08.12
# script to invoke sugarj from command line
# using latest-available classes

# find base directory of sugarj
classpath=`u/classpath`

exec java -Xss64m -Xmx1024m -cp "$classpath" org.sugarj.driver.cli.Main $*
