#!/bin/bash
# cai 17.08.12
# script to print classpath

# requires STRATEGO_JAR
strategojar=`echo $STRATEGO_JAR`


# find base directory of sugarj
sugarj="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"
script="$sugarj/deployment/cli-scripts"
base="$sugarj/base-lang/bin"
common="$sugarj/common/bin"
compiler="$sugarj/compiler/bin"
stdlib="$sugarj/stdlib/bin"
cliroot="$sugarj/compiler"
clijars="$strategojar:$cliroot/make_permissive.jar:$cliroot/commons-cli-1.2.jar"
langroot="$sugarj/languages"
langlibs="$langroot/haskell/bin:$langroot/java/bin:$langroot/prolog/bin"

# essential paths
classpath="$compiler:$clijars:$base:$common:$stdlib:$langlibs"

# what we try to combine
# somehow the nativebundle does not cooperate no matter what I do with it
# zip, jar, etc won't help the star locate SDFBundleCommand.class
sdfbundle="$script/native"
classpath="$classpath:$sdfbundle"
classpath="$classpath:$script/jars/*"

exec echo "$classpath"
